version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.16.1
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
        - cp -R node_modules/ dist/node_modules
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
    - .platform/**/*
    - .ebextensions/*
  discard-paths: no

